namespace Guiguimmo.Game.Models;

public static class GameMap
{
  public const int GRASS = 1;
  public const int WALL = 2;
  public const int WATER = 3;
  public const int ROAD = 4;

  public static readonly int[,] CurrentMap = new int[,]
  {
    { WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL },
    { WALL, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
    { WALL, GRASS, WATER, GRASS, GRASS, WATER, GRASS, GRASS, WATER, GRASS, GRASS, WATER, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
    { WALL, GRASS, WATER, GRASS, GRASS, WATER, GRASS, GRASS, WATER, GRASS, GRASS, WATER, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
    { WALL, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
    { WALL, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
    { WALL, GRASS, WATER, GRASS, GRASS, WATER, GRASS, GRASS, WATER, GRASS, GRASS, WATER, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
    { WALL, GRASS, WATER, GRASS, GRASS, WATER, GRASS, GRASS, WATER, GRASS, GRASS, WATER, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
    { WALL, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, WALL },
    { WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL }
  };

  public static int MapWidth => CurrentMap.GetLength(1);
  public static int MapHeight => CurrentMap.GetLength(0);

  public static bool IsTileSolid(int tileId)
  {
    return tileId == WALL || tileId == WATER;
  }

  public static int GetTile(int x, int y)
  {
    if (x < 0 || x >= MapWidth || y < 0 || y >= MapHeight)
    {
      return WALL;
    }

    return CurrentMap[y, x];
  }
}